site_name: fits2db

nav:
  - index.md
  - User Guide: 
    - Overview: user-guide/overview.md
    - About fits2db: user-guide/about-us.md
    - Installation: user-guide/installation.md
    - Examples: user-guide/examples.md
    - Troubleshooting: user-guide/trouble.md
  - Contribution guide: 
    - Get source: contribution/contribution.md
  - API reference:
    - CLI reference: reference/reference.md
    - DB reference: reference/database.md

  
repo_url: https://github.com/pmodwrc/fits2db 
repo_name: pmodwrc/fits2db

theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.indexes
  icon:
    repo: fontawesome/brands/git-alt
  logo: layout/images/logo.png
  palette: 
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode



plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
  - tags
  - search
  - git-revision-date-localized:
      type: date
  - git-authors
  - glightbox



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - mkdocs-click
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js